Fix deprecated copy from @ember/object/internal
BBVAEngineering/ember-route-helpers pull request #10
Opened 2018-10-09 15:56 UTC by xomaczar

2018-10-10 12:25 UTC, adrigzr approved these changes

2018-10-10 12:26 UTC, adrigzr requested changes
Hi @xomaczar,

Thanks for the PR. Please, checkout package-lock.json. It is not needed.

Regards

2018-10-10 12:36 UTC, next-juanantoniogomez submitted a review, later dismissed

2018-10-10 14:16 UTC, xomaczar commented
@adrigzr done

2018-10-15 13:33 UTC, xomaczar commented
cc @adrigzr can you merge and `npm publish` a new version? Thx.

2018-10-17 12:03 UTC, adrigzr approved these changes

2018-10-17 12:03 UTC, merged